[package]
name = "parser2"
version = "0.0.1"
authors = ["Hyunsik Choi <hyunsik@apache.org>"]

[lib]
name = "parser2"
path = "lib.rs"

[dependencies]
common = { path = "../common" }

regex = "0.1.47"
bitflags = "0.7"


