[package]
name = "test-util"
version = "0.0.1"
authors = ["Hyunsik Choi <hyunsik@apache.org>"]

[lib]
name = "test_util"
path = "lib.rs"

[dependencies]
difference = "0.4.1"
env_logger = "0.3.2"
itertools = "0.4.3"
log = "0.3.4"


