[package]
authors = ["The Tomakam Project Developers"]
name = "tc_driver"
version = "0.0.0"

[lib]
name = "tc_driver"
path = "lib.rs"
crate-type = ["dylib"]

[dependencies]
syntax = { path = "../libsyntax" }
tc_hir = { path = "../libtc_hir" }

getopts = "0.2.14"