[package]
name = "parser"
version = "0.0.1"
authors = ["Jihoon Son <jihoonson@apache.org>"]

[lib]
name = "parser"
path = "lib.rs"

[dependencies]
regex = "0.1.47"
# regex_macros = "0.1.27"

[dependencies.plan]
path = "../plan"

[dependencies.common]
path = "../common"
