[package]
name = "syntax"
version = "0.1.0"
authors = ["Hyunsik Choi <hyunsik@apache.org>"]

[lib]
name = "syntax"
path = "lib.rs"

[dependencies]
log = "0.3.4"
env_logger = "0.3.2"
bitflags = "0.4.0"
term = "0.4.4"
rustc-serialize = "0.3.16"
