[package]
name = "tc_hir"
version = "0.0.1"
authors = [ "Hyunsik Choi <hyunsik.choi@gmail.com>" ]

[lib]
name = "tc_hir"
path = "lib.rs"

[dependencies]
itertools = "0.4.3"
rustc-serialize = "0.3.16"

common = { path = "../common" }
util = { path = "../util" }
syntax = { path = "../libsyntax" }