[package]
name = "driver"
version = "0.0.1"
authors = [ "Hyunsik Choi <hyunsik.choi@gmail.com>" ]

[[bin]]
name = "flang"
path = "driver.rs"

[dependencies]
env_logger = "0.3.2"
getopts = "0.2.14"
log = "0.3.4"
rl-sys = "0.5.2"

libdriver = { path = "../../lib/driver" }