[package]
name = "sql"
version = "0.0.1"
authors = [ "Hyunsik Choi <hyunsik.choi@gmail.com>" ]

[lib]
name = "sql"
path = "lib.rs"

[dependencies]
itertools = "0.4.3"

[dependencies.common]
path = "../common"