[package]
name = "default_package"
version = "0.0.1"
authors = [ "Hyunsik Choi <hyunsik.choi@gmail.com>" ]

[lib]
name = "default_package"
path = "lib.rs"

[dependencies]
rand = "0.3.12"

[dependencies.common]
path = "../common"
